### ISSUE TITLE
Unserialize callback throws error when callback has parameter

### ISSUE THREAD

**Issue by xarasbir** [botman/botman#386]
- BotMan Version: 1.5.6
- PHP Version: 7.0
- Messaging Service(s): None yet, using botman:tinker
- Cache Driver: File

### Description:
When a callback closure has a parameter, the code throws an error when `repeat()` is called. This is caused by `\Mpociot\BotMan\Conversation@repeat` line 129. 

### Steps To Reproduce:
Snippet from conversation : 
```
return $this->ask("Please enter date (DD/MM/YYYY)?", [
            [
                'pattern' => '(?:0[1-9]|[1-2][0-9]|3[0-1])/(?:0[1-9]|1[0-2])/[0-9]{4}',
                'callback' => function (Answer $answer) {
                    $this->startDate = Carbon::createFromFormat('d/m/Y', $answer->getText());
                    $this->confirmStartDate();
                }
            ],
            [
                'pattern' => '.*',
                'callback' => function () {
                    $this->say('Sorry I did not get that.');
                    //
                    $this->repeat('Please enter a date in the following format (DD/MM/YYY). Example : 15/12/2017 for December 15, 2007 ');
                }
            ],
        ]);
```

From error log
```
[2017-05-18 08:38:23] local.ERROR: ErrorException: unserialize() expects parameter 1 to be string, object given in /Library/WebServer/Documents/botservation.com/vendor/mpociot/botman/src/Mpociot/BotMan/Conversation.php:129
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'unserialize() e...', '/Library/WebSer...', 129, Array)
#1 /Library/WebServer/Documents/botservation.com/vendor/mpociot/botman/src/Mpociot/BotMan/Conversation.php(129): unserialize(Object(Closure))
#2 [internal function]: Mpociot\BotMan\Conversation->Mpociot\BotMan\{closure}(Array, 0)
#3 /Library/WebServer/Documents/botservation.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(613): array_map(Object(Closure), Array, Array)
#4 /Library/WebServer/Documents/botservation.com/vendor/mpociot/botman/src/Mpociot/BotMan/Conversation.php(132): Illuminate\Support\Collection->map(Object(Closure))
#5 /Library/WebServer/Documents/botservation.com/app/Conversations/ExampleConversation.php(103): Mpociot\BotMan\Conversation->repeat('Please enter a ...')
```

I might be wrong by getting `Answer` from the parameter but I can't find any reference from the documentation where to get answer from within the callback.

**Comment by christophrumpel** [comment]
Hey @xarasbir , I will look into that later today.
