### ISSUE TITLE
Undefined index: type in FacebookImageDriver.php

### ISSUE THREAD

**Issue by temxby** [botman/botman#463]
- BotMan Version: 1.5.7
- PHP Version: 5.6

### Description:
I'm write
```
$bot->hears('hi', function (BotMan $bot) {
    $bot->reply('hello');
})->driver(FacebookDriver::DRIVER_NAME);
```
After sending in Messenger message "hi", a i have this error in logs

```
[2017-07-09 14:34:47] local.ERROR: exception 'ErrorException' with message 'Undefined index: type' in /home/admin/web/test.com/public_html/vendor/mpociot/botman/src/Mpociot/BotMan/Drivers/FacebookImageDriver.php:25
Stack trace:
#0 /home/admin/web/test.com/public_html/vendor/mpociot/botman/src/Mpociot/BotMan/Drivers/FacebookImageDriver.php(25): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/home/admin/we...', 25, Array)
#1 [internal function]: Mpociot\BotMan\Drivers\FacebookImageDriver->Mpociot\BotMan\Drivers\{closure}(Array, 0)
#2 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Support/Arr.php(567): array_filter(Array, Object(Closure), 1)
#3 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Support/Collection.php(362): Illuminate\Support\Arr::where(Array, Object(Closure))
#4 /home/admin/web/test.com/public_html/vendor/mpociot/botman/src/Mpociot/BotMan/Drivers/FacebookImageDriver.php(26): Illuminate\Support\Collection->filter(Object(Closure))
#5 [internal function]: Mpociot\BotMan\Drivers\FacebookImageDriver->Mpociot\BotMan\Drivers\{closure}(Array, 0)
#6 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Support/Arr.php(567): array_filter(Array, Object(Closure), 1)
#7 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Support/Collection.php(362): Illuminate\Support\Arr::where(Array, Object(Closure))
#8 /home/admin/web/test.com/public_html/vendor/mpociot/botman/src/Mpociot/BotMan/Drivers/FacebookImageDriver.php(30): Illuminate\Support\Collection->filter(Object(Closure))
#9 /home/admin/web/test.com/public_html/vendor/mpociot/botman/src/Mpociot/BotMan/DriverManager.php(176): Mpociot\BotMan\Drivers\FacebookImageDriver->matchesRequest()
#10 /home/admin/web/test.com/public_html/vendor/mpociot/botman/src/Mpociot/BotMan/BotManFactory.php(40): Mpociot\BotMan\DriverManager->getMatchingDriver(Object(Illuminate\Http\Request))
#11 /home/admin/web/test.com/public_html/vendor/mpociot/botman/src/Mpociot/BotMan/BotManServiceProvider.php(21): Mpociot\BotMan\BotManFactory::create(Array, Object(Mpociot\BotMan\Cache\LaravelCache), Object(Illuminate\Http\Request), Object(Mpociot\BotMan\Storages\Drivers\FileStorage))
#12 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Mpociot\BotMan\BotManServiceProvider->Mpociot\BotMan\{closure}(Object(Illuminate\Foundation\Application), Array)
#13 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#14 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('botman')
#15 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('botman')
#16 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(106): Illuminate\Foundation\Application->make('botman')
#17 /home/admin/web/test.com/public_html/app/Http/Controllers/Api/FacebookBotController.php(22): app('botman')
#18 [internal function]: App\Http\Controllers\Api\FacebookBotController->handle()
#19 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#20 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('handle', Array)
#21 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\FacebookBotController), 'handle')
#22 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#23 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Routing\Route->run()
#24 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#30 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#34 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#35 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#36 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#37 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /home/admin/web/test.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 /home/admin/web/test.com/public_html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  
```
Before everything worked fine. The code did not change

**Comment by mpociot** [comment]
Fixed in 1.5.8
