### ISSUE TITLE
Conversion's Closure is called in different way when driver's serializesCallbacks is true

### ISSUE THREAD

**Issue by e2haining** [botman/botman#690]
- BotMan Version: 2.1.5
- PHP Version: 7.2.0
- Messaging Service(s):
- Cache Driver:

### Description:
In the Conversion's Closure function, I used $this to refer the Conversation object,
It works fine when using web-driver, but when using SlackRTMDriver, it throws an Exception
saying that the "Using $this when not in object context"

```
#0 [internal function]: {closure}(Object(BotMan\BotMan\Messages\Incoming\Answer), Object(App\Conversations\AskWhatConversation))
#1 /var/www/e2info/vendor/botman/botman/src/Traits/HandlesConversations.php(290): call_user_func_array(Object(Closure), Array)
#2 /var/www/e2info/vendor/botman/botman/src/Traits/HandlesConversations.php(270): BotMan\BotMan\BotMan->prepareConversationClosure(Object(Closure), Object(App\Conversations\AskWhatConversation), Array)
#3 /var/www/e2info/vendor/botman/botman/src/Traits/HandlesConversations.php(232): BotMan\BotMan\BotMan->callConversation(Object(Closure), Array, Object(BotMan\BotMan\Messages\Incoming\IncomingMessage), Array)
#4 /var/www/e2info/vendor/laravel/framework/src/Illuminate/Support/Collection.php(337): BotMan\BotMan\BotMan->BotMan\BotMan\Traits\{closure}(Object(BotMan\BotMan\Messages\Incoming\IncomingMessage), 0)
#5 /var/www/e2info/vendor/botman/botman/src/Traits/HandlesConversations.php(234): Illuminate\Support\Collection->each(Object(Closure))
#6 /var/www/e2info/vendor/botman/botman/src/BotMan.php(380): BotMan\BotMan\BotMan->loadActiveConversation()
#7 /var/www/e2info/vendor/botman/driver-slack/src/Factory.php(67): BotMan\BotMan\BotMan->listen()
#8 /var/www/e2info/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): BotMan\Drivers\Slack\Factory->BotMan\Drivers\Slack\{closure}('message', Object(Slack\Payload))
#9 /var/www/e2info/vendor/mpociot/slack-client/src/RealTimeClient.php(402): Slack\RealTimeClient->emit('_internal_messa...', Array)
#10 /var/www/e2info/vendor/mpociot/slack-client/src/RealTimeClient.php(121): Slack\RealTimeClient->onMessage(Object(Devristo\Phpws\Messaging\WebSocketMessage))
#11 /var/www/e2info/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Slack\RealTimeClient->Slack\{closure}(Object(Devristo\Phpws\Messaging\WebSocketMessage))
#12 [internal function]: Evenement\EventEmitter->emit('message', Array)
....
```
At last I found the problem is in https://github.com/botman/botman/blob/master/src/Traits/HandlesConversations.php

SlackRTMDriver is not SerializableClosure, so the bindTo is not executed.

```
    protected function prepareConversationClosure($next, Conversation $conversation, array $parameters)
    {
        if ($next instanceof SerializableClosure) {
            $next = $next->getClosure()->bindTo($conversation, $conversation);
        }
        $parameters[] = $conversation;
        call_user_func_array($next, $parameters);
    }
```
To keep the same logic when it is not a SerializableClosure
I think It should be fixed as following:
```
        if ($next instanceof SerializableClosure) {
            $next = $next->getClosure()->bindTo($conversation, $conversation);
        } elseif ($next instanceof Closure) {
            $next = $next->bindTo($conversation, $conversation);
        }
```

**Comment by mpociot** [comment]
@e2haining can you send me a pull request with your changes?

**Comment by mpociot** [comment]
Thank you!
