### ISSUE TITLE
Conversation Class not found

### ISSUE THREAD

**Issue by MarkCupitt** [botman/botman#732]
Hi There, I'm having what I think is a dumb mistake on my part, getting conversions to work .. I get ..

` PHP Fatal error:  Class 'Conversation' not found in` 

This is probably obvious . but I just cannot see it 

Composer.Json

```
{
    "require": {
        "botman/botman": "^2.3",
        "botman/driver-facebook": "^1.6",
        "cache/memcache-adapter": "^1.0",
        "cache/doctrine-adapter": "^1.0",
        "cache/memcached-adapter": "^1.0"
    }
}
```

```
// --------------------------------------------------------------------------------	
// Initialize
// --------------------------------------------------------------------------------	
use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;

use BotMan\BotMan\Drivers\DriverManager;

use BotMan\BotMan\Cache\Psr6Cache;
use BotMan\BotMan\Cache\DoctrineCache;

//use BotMan\BotMan\Messages\Conversations;

use Doctrine\Common\Cache\MemcachedCache;
use Cache\Adapter\Doctrine\DoctrineCachePool;

DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);

// Load all the Conversations
require 'conversations/include.php';

// --------------------------------------------------------------------------------	
// Set up Persistent Cache for the Conversations
// --------------------------------------------------------------------------------			
$memcached = new \Memcached();
$memcached->addServer('localhost', 11211);

// Create a instance of Doctrine's MemcachedCache
$doctrineCache = new MemcachedCache();
$doctrineCache->setMemcached($memcached);

// Wrap Doctrine's cache with the PSR-6 adapter
$pool = new DoctrineCachePool($doctrineCache);
		
// Create BotMan instance
$botman = BotManFactory::create($config, new Psr6Cache($pool));

// Give the bot something to listen for.
$botman->hears('Check you Pension Options Now', function (BotMan $bot) {
    $bot->startConversation(new getStarted);
	});

// Start listening
$botman->listen();

```

getStarted.php has this in it ..

```
class getStarted extends Conversation
{
    protected $firstname;

    protected $email;

    public function askFirstname()
    {
        $this->ask('Hello! What is your firstname?', function(Answer $answer) {
            // Save result
            $this->firstname = $answer->getText();

            $this->say('Nice to meet you '.$this->firstname);
            $this->askEmail();
        });
    }

    public function askEmail()
    {
        $this->ask('One more thing - what is your email?', function(Answer $answer) {
            // Save result
            $this->email = $answer->getText();

            $this->say('Great - that is all we need, '.$this->firstname);
        });
    }


    public function run()
    {
        // This will be called immediately
        $this->askFirstname();
    }
}
```

Thanks Mark

**Comment by christophrumpel** [comment]
Hey @MarkCupitt , it looks like you forgot import BotMans pas conversation class `use BotMan\BotMan\Messages\Conversations\Conversation;` inside your getStarted class.

**Comment by MarkCupitt** [comment]
Hey thnaks, I thought I had done that, but it worked, however I now get

```

**Comment by MarkCupitt** [comment]
OK, I made some progress, this is on Ubuntu

```
sudo apt-get install php-curl
sudo apt-get install php-oauth
sudo service apache2 restart
``
composer update was not installing symfony, which is needed in 
 `\vendor\botman\botman\src\Http\Curl.php` but after repeated attempts, it finally decided to install it .. no idea what triggered it .. maybe the installation of the php extensions

**Comment by MarkCupitt** [comment]
So now I am getting a PHP Fatal error for what appears to be an invalid user ..

```
[Fri Mar 02 03:22:02.516580 2018] [:error] [pid 19854] [client 173.252.86.66:39460] PHP Fatal error:  Uncaught BotMan\\Drivers\\Facebook\                     \Exceptions\\FacebookException: Error sending payload: (#100) No matching user found in /var/www/html/facebook.capitalplatforms.net/vendo                     r/botman/driver-facebook/src/FacebookDriver.php:442\nStack trace:\n#0 /var/www/html/facebook.capitalplatforms.net/vendor/botman/driver-fa                     cebook/src/FacebookDriver.php(365): BotMan\\Drivers\\Facebook\\FacebookDriver->throwExceptionIfResponseNotOk(Object(Symfony\\Component\\H                     ttpFoundation\\Response))\n#1 /var/www/html/facebook.capitalplatforms.net/vendor/botman/botman/src/BotMan.php(616): BotMan\\Drivers\\Face                     book\\FacebookDriver->sendPayload(Array)\n#2 [internal function]: BotMan\\BotMan\\BotMan->BotMan\\BotMan\\{closure}(Array)\n#3 /var/www/h                     tml/facebook.capitalplatforms.net/vendor/mpociot/pipeline/src/Pipeline.php(114): call_user_func_array(Object(Closure), Array)\n#4 [intern                     al function]: Mpociot\\Pipeline\\Pipeline->Mpociot\\Pipeline\\{closure}(Array)\n#5 /var/www/html/facebook.capitalplatforms.net/vendor/mpo                     ciot/pipeline/src/Pipeline.php(102): call_user_func_array( in /var/www/html/facebook.capitalplatforms.net/vendor/botman/driver-facebook/s                     rc/FacebookDriver.php on line 442
```

**Comment by MarkCupitt** [comment]
Oops, sorry, my bad, was a typo in the Access Token .. but will leave this here in case it catches someone else out

I get the converstation to respond now ..

It may help to list the requirements for the php setup to get it all to work on the install page somewhere ..

I started with a brand new LAMP php 7.x installation

**Comment by christophrumpel** [comment]
Hey @MarkCupitt , I'm glad it works now! Yeah right, CURL is a requirement. You could also make a PR to the docs. That would help too.
