### ISSUE TITLE
Error when calling say() from skipsConversation()

### ISSUE THREAD

**Issue by mkopinsky** [botman/botman#824]
- BotMan Version: 2.3.3
- PHP Version: 7.1.14
- Messaging Service(s): web (Botman Studio)
- Cache Driver: Botman Studio default

### Description:

I wanted to have a `help` message that could be triggered at any point within a conversation. (This is separate from a global `help` keyword which triggers when outside of a conversation).

### Steps To Reproduce:
For context, my controller has:
```php
        $botman->hears('help', function($bot) {
            $bot->reply('We will text you every morning and afternoon asking for your blood pressure.');
        });
```
In my conversation:
```php
    public function skipsConversation(IncomingMessage $message)
    {
        if ($message->getText() == 'help') {
            $this->say('Please send in your blood pressure formatted like this: XXX/YY, e.g. 123/89');
            return true;
        }

        return false;
    }
```

When I send in `help` during the conversation, I get this stack trace:
```
[2018-06-05 20:23:04] local.ERROR: Call to a member function reply() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function reply() on null at /Users/kopinsky/code/botman-playground/vendor/botman/botman/src/Messages/Conversations/Conversation.php:170)
[stacktrace]
#0 /Users/kopinsky/code/botman-playground/app/Conversations/BPConversation.php(46): BotMan\\BotMan\\Messages\\Conversations\\Conversation->say('Please send in ...')
#1 /Users/kopinsky/code/botman-playground/vendor/botman/botman/src/Traits/HandlesConversations.php(181): App\\Conversations\\BPConversation->skipsConversation(Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage))
#2 /Users/kopinsky/code/botman-playground/vendor/laravel/framework/src/Illuminate/Support/Collection.php(397): BotMan\\BotMan\\BotMan->BotMan\\BotMan\\Traits\\{closure}(Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage), 0)
#3 /Users/kopinsky/code/botman-playground/vendor/botman/botman/src/Traits/HandlesConversations.php(235): Illuminate\\Support\\Collection->each(Object(Closure))
#4 /Users/kopinsky/code/botman-playground/vendor/botman/botman/src/BotMan.php(396): BotMan\\BotMan\\BotMan->loadActiveConversation()
#5 /Users/kopinsky/code/botman-playground/app/Http/Controllers/BotManController.php(45): BotMan\\BotMan\\BotMan->listen()
#6 [internal function]: App\\Http\\Controllers\\BotManController->handle()
....
```

**Comment by mpociot** [comment]
You can not use the `say` command inside of the `skipsConversation` method.

An additional approach would be to define the `help` command like this:

```php
$botman->hears('help', function($bot) {
    $bot->reply('We will text you every morning and afternoon asking for your blood pressure.');
})->skipsConversation();
```

**Comment by mkopinsky** [comment]
In my use case, the `help` command has two different responses - one ("Please send in your Blood Pressure...") when the conversation is active, and another ("We will text you every morning...") at other times. I don't see any way to accommodate that use case with the command definition you showed.

This isn't a show stopper, but I do think it's an enhancement that would be worth supporting.
