### ISSUE TITLE
Starting Conversation from Queue

### ISSUE THREAD

**Issue by lucadegasperi** [botman/botman#906]
- BotMan Version: 2.4.1
- PHP Version: 7.2.6
- Messaging Service(s): telegram
- Cache Driver: file

### Description:
Using the `ExampleConversation.php` file I've tried to create a new conversation from a Notification, by implementing a custom notification channel. When the notification is queued up I get the following error and stack trace. Starting the conversation normally when calling a command works just fine.
I've tried adding the `ShouldQueue` interface to the conversation but nothing changes.

Can you help me please?

```
[2018-10-23 14:37:57] local.ERROR: fclose(): supplied resource is not a valid stream resource {"exception":"[object] (ErrorException(code: 0): fclose(): supplied resource is not a valid stream resource at /vendor/predis/predis/src/Connection/StreamConnection.php:275)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'fclose(): suppl...', '...', 275, Array)
#1 /vendor/predis/predis/src/Connection/StreamConnection.php(275): fclose(Resource id #832)
#2 /vendor/predis/predis/src/CommunicationException.php(74): Predis\\Connection\\StreamConnection->disconnect()
#3 /vendor/predis/predis/src/Connection/AbstractConnection.php(155): Predis\\CommunicationException::handle(Object(Predis\\Connection\\ConnectionException))
#4 /vendor/predis/predis/src/Connection/StreamConnection.php(298): Predis\\Connection\\AbstractConnection->onConnectionError('Error while wri...')
#5 /vendor/predis/predis/src/Connection/StreamConn\ction.php(394): Predis\\Connection\\StreamConnection->write('*6\
\4\
\VAL\
$...')
#6 /vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\\Connection\\StreamConnection->writeRequest(Object(Predis\\Command\\ServerEval))
#7 /vendor/predis/predis/src/Client.php(331): Predis\\Connection\\AbstractConnection->executeCommand(Object(Predis\\Command\\ServerEval))
#8 /vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand(Object(Predis\\Command\\ServerEval))
#9 /vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(114): Predis\\Client->__call('eval', Array)
#10 /vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(214): Illuminate\\Redis\\Connections\\Connection->command('eval', Array)
#11 /vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(205): Illuminate\\Redis\\Connections\\Connection->__call('eval', Array)
#12 /vendor/laravel/horizon/src/RedisQueue.php(108): Illuminate\\Queue\\RedisQueue->migrateExpiredJobs('queues:local:de...', 'queues:local')
#13 /vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(188): Laravel\\Horizon\\RedisQueue->migrateExpiredJobs('queues:local:de...', 'queues:local')
#14 /vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(164): Illuminate\\Queue\\RedisQueue->migrate('queues:local')
#15 /vendor/laravel/horizon/src/RedisQueue.php(92): Illuminate\\Queue\\RedisQueue->pop('local')
#16 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(247): Laravel\\Horizon\\RedisQueue->pop('local')
#17 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(107): Illuminate\\Queue\\Worker->getNextJob(Object(Laravel\\Horizon\\RedisQueue), 'local')
#18 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('redis', 'local', Object(Illuminate\\Queue\\WorkerOptions))
#19 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'local')
#20 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#21 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 /vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 /vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#26 /vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
"}
```

### Steps To Reproduce:

```TelegramChannel.php```

```php
public function send($notifiable, Notification $notification)
{
        $botman = app('botman');

        $message = $notification->toTelegram($notifiable);

        $botman->startConversation($message, $notifiable->getTelegramId(), TelegramDriver::class);
}
```

```ExampleNotification.php```

```php
public function toTelegram($notifiable)
{
    return new ExampleConversation();
}
```

**Comment by mintunitish** [comment]
Any update on this? Facing the issue still.

**Comment by sazzadahmed41** [comment]
Any Update with this issue I am facing same issue here?
